version: '3.7'
services:
    nest-api:
        container_name: nest-api 
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        restart: always
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        command: npm run start:dev
        depends_on:
            - postgres
        env_file:
            - .env

    postgres:
        container_name: postgres
        image: postgres:alpine
        restart: always
        env_file:
            - .env
        volumes:
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh
        ports:
            - 5432:5432


    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
