version: '3.3'
services:
    nest-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-api 
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - postgres
        env_file:
            - .env

    postgres:
        image: postgres:alpine
        restart: always
        env_file:
            - .env

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
